### PR TITLE
Adding lemonade recipe

### PR DESCRIPTION
**Pull request by gouthamvaleti**
When life gives you lemons, merge the github branch

### CODE REVIEW

**Comment by ka3ineli** [comment]
That's a motto to live by

**Comment by ka3ineli** [comment]
LGTM:+1: let's :hankey: it

**Comment by ka3ineli** [comment]
I meant :ship: it but that works too!

**Comment by ka3ineli** [comment]
:hankey: :hamburger: muahahhaha

**Comment by gouthamvaleti** [comment]
:dancers:

**Pull request merged**
