### PR TITLE
Add iced tea recipe

### PR DESCRIPTION
**Pull request by sdasgupta17**

### CODE REVIEW

**Comment by ka3ineli** [comment]
What kind of tea is it??

**Comment by gouthamvaleti** [comment]
It's becomes cold by chilling with lemons!?!?

**Comment by melissa12345** [comment]
LGTM:+1 :+1 :+1 :100: :8ball:

**Comment by ka3ineli** [comment]
:hankey: :hankey:

**Comment by ka3ineli** [comment]
DID YOU JUST MERGE OUR BRANCHES!?!?!?!

**Comment by ka3ineli** [comment]
How dare you.

**Pull request merged**
